Below are functions used to clean the data.

```{r}
#######################################################
remove_na <- function(df) { ## Automatize the removal of missing observations.
  n_obs <- nrow(df)
  missing <- rep(FALSE, n_obs)
  for (obs_ind in 1:n_obs) {
    obs <- df[obs_ind, ]
    n_missing <- sum(is.na(obs))
    if(n_missing > 0) {
      missing[obs_ind] <- TRUE
    }
  }
  df_red <- df[!missing, ]

  return(df_red)
}
#######################################################
to_factors <- function(df) { ## Turn all character variables to factors.
  n_vars <- ncol(df)
  for (var_ind in 1:n_vars) {
    var <- df[, var_ind]
    if (class(var) == "character") {
      df[, var_ind] <- factor(var)
    }
  }
  return(df)
}
```

Load data

```{r}
FemaleLabor <- data.frame(read.csv("00_LaborForceData.csv"))
EducationExp <- data.frame(read.csv("00_GovEducationExpense.csv"))
BirthRate <- data.frame(read.csv("00_BirthRate.csv"))
FertilityRate <- data.frame(read.csv("00_FertilityRate.csv"))
ParentalLeave <- data.frame(read.csv("00_ParentalLeave.csv"))
TertiaryEnroll <- data.frame(read.csv("00_TertiaryEnrollmentRate.csv"))
```

We'll remove any unnecessary variables from the datasets then apply the functions defined above to each dataset.

```{r}
keep_col <- c("REF_AREA", "REF_AREA_LABEL", "TIME_PERIOD", "OBS_VALUE")

edu_clean <- EducationExp[,keep_col]
flabor_clean <- FemaleLabor[,keep_col]
brate_clean <- BirthRate[,keep_col]
fert_clean <- FertilityRate[,keep_col]
leave_clean <- ParentalLeave[,-c(1,2)]
enroll_clean <- TertiaryEnroll[,-c(1,2)]
```

```{r}
#will use the remove_na function to clear any missing observations if any
remove_na(EducationExp)
remove_na(LaborData)
#uses to_factors to convert all data into factors if not already
to_factors(EducationExp)
to_factors(LaborData)
```











